# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://recarreira.github.io
title: Renata Carreira
subtitle: 
fulltitle: Renata Carreira, <br><em>desenvolvedora</em>, <br>carioca
author: Renata Carreira
simple_search: http://google.com/search
about_content: Renata Carreira, estudante, desenvolvedora, gamer, DCnauta, RPGista, viciada em series, que brinca de pintar quadros nas horas vagas e desconhece vida social fora de uma mesa de jogo. Ah, e que mora com alguém.
description:

# All text content for both languages:
pt-BR: &pt-BR
  recent_projects: projetos recentes
  recent_posts: últimos artigos
  archive: arquivo
  found: contato
  contact: contato
  about: sobre mim
  rss_title: assine

en-US: &en-US
  recent_projects: recent project
  recent_posts: last posts
  archive: arquives
  found: found on
  contact: contact at
  about: about me
  rss_title: feed

i18n:
  <<: *pt-BR

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/RenataCarreiraDev
subscribe_email:
# RSS feeds can list your email address if you like
email: contato@renatacarreira.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Continue lendo &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: recarreira
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: false

# Twitter
twitter_user: Renata_Carreira
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: small

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# About.me
aboutme_user: re.carreira

# Facebook
facebook_user:

# Linkedin
linkedin_user:

# Foursquare
foursquare_user:

# deviantART
deviantart_user:

# Flickr
flickr_user:

# Last.fm
lastfm_user:

# stack overflow
stackoverflow_user:

# Quora
quora_user:

# Disqus Comments
disqus_short_name: renatacarreira
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-41037789-1

# Facebook Like
facebook_like: true